-- SUBQUERIES --

USE EMPLOYEE;

-- 1.Display employee(s) with highest salary
SELECT * FROM EMPLOYEE WHERE SAL = (SELECT MAX(SAL) FROM EMPLOYEE);

-- 2. Find highest paid CLERK
SELECT
EMPNO,
ENAME
FROM
EMPLOYEE
WHERE JOB = 'CLERK'
AND SAL = ( SELECT MAX(SAL) FROM EMPLOYEE WHERE JOB = 'CLERK');

-- 3. Display SALESMAN whose salary is greater than highest CLERK salary
SELECT
ENAME 
FROM EMPLOYEE
WHERE JOB = 'SALESMAN'
AND SAL >
(
SELECT MAX(SAL) FROM EMPLOYEE WHERE JOB = 'CLERK');


-- 4. CLERK whose salary is between JAMES and SCOTT salary
SELECT
ENAME 
FROM EMPLOYEE
WHERE JOB = 'CLERK'
AND SAL > (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'JAMES')
AND SAL < (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'SCOTT');


-- 5. CLERK whose salary is > JAMES OR < SCOTT
SELECT
ENAME 
FROM EMPLOYEE
WHERE JOB = 'CLERK'
AND SAL > (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'JAMES')
OR SAL < (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'SCOTT');



-- 6.Employee with highest salary in each department
SELECT 
ENAME,
DEPTNO,
SAL
FROM EMPLOYEE E
WHERE SAL = (
 SELECT MAX(SAL) FROM EMPLOYEE WHERE DEPTNO = E. DEPTNO) ORDER BY DEPTNO;
 
 
 
 -- 7.Employee with highest salary in each job
 SELECT 
 ENAME, 
 JOB,
 SAL
 FROM EMPLOYEE E
 WHERE SAL = ( SELECT MAX(SAL) FROM EMPLOYEE WHERE JOB = E.JOB);
 
 -- 8. Employees working in ACCOUNTING department
 SELECT
 ENAME,
 JOB,
 DEPTNO
 FROM EMPLOYEE 
 WHERE DEPTNO = 
 (
    SELECT DEPTNO FROM DEPARTMENT WHERE DNAME = 'ACCOUNTING');
    
    
-- 9. Employees working in CHICAGO location
SELECT
 ENAME,
 JOB,
 DEPTNO
 FROM EMPLOYEE 
 WHERE DEPTNO = 
 (
    SELECT DEPTNO FROM DEPARTMENT WHERE LOCATION = 'CHICAGO');




-- 10. Department-wise job salary greater than MANAGER max salary
SELECT 
JOB,
SUM(SAL) AS TOTAL_SAL
FROM EMPLOYEE
GROUP BY JOB
HAVING
SUM(SAL) > (SELECT MAX(SAL) FROM EMPLOYEE WHERE JOB = 'MANAGER');




















 