USE EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE HIREDATE < '1980-06-30'  OR HIREDATE > '1981-12-31';


SELECT ENAME FROM EMPLOYEE WHERE ENAME LIKE '_A%';


SELECT * FROM EMPLOYEE WHERE LENGTH(ENAME) = 5;

SELECT * FROM EMPLOYEE WHERE JOB NOT IN ('CLERK','SALESMAN','ANALYST');



