USE EMPLOYEE;
SELECT ENAME, JOB, SAL FROM EMPLOYEE WHERE DEPTNO=30  ORDER BY SAL DESC;

SELECT * FROM EMPLOYEE WHERE ENAME LIKE 'A_L_N';

SELECT * FROM EMPLOYEE WHERE ENAME LIKE 'S%';

SELECT * FROM EMPLOYEE WHERE ENAME LIKE '%S';

SELECT ENAME FROM EMPLOYEE WHERE JOB IN('CLERK', 'SALESMAN', 'ANALYST') OR DEPTNO IN(10,20,40);

SELECT EMPNO, ENAME, COMM FROM EMPLOYEE WHERE COMM IS NOT NULL AND COMM > 0;

SELECT EMPNO, ENAME, (SAL + IFNULL(COMM, 0)) AS TOTAL_SAL 
FROM EMPLOYEE;

SELECT EMPNO, ENAME, SAL,SAL*12 AS ANNUAL_SALARY FROM EMPLOYEE;


SELECT * FROM EMPLOYEE WHERE JOB = 'CLERK' AND SAL > 3000;


SELECT * FROM EMPLOYEE WHERE JOB IN('CLERK', 'SALESMAN', 'ANALYST') AND SAL > 3000;



