USE EMPLOYEE;
-- 1. COMPUTE THE NO OF DAYES REMAINING IN THIS YEAR
SELECT
DATEDIFF(
MAKEDATE(YEAR(CURDATE()),1),
CURDATE()
) AS DAYS_REMAINING;


-- 2. Find highest salary, lowest salary and difference
SELECT
MAX(SAL) AS HIGHEST_SALARY,
MIN(SAL) AS LOWEST_SALARY,
MAX(SAL) - MIN(SAL) AS DIFFERENCE FROM EMPLOYEE;


-- 3. Display employees whose commission is greater than 25% of salary
SELECT * FROM EMPLOYEE WHERE COMM > SAL * 0.25;


-- 4. Display employee name with salary formatted in dollars
SELECT ENAME,CONCAT('$', FORMAT(SAL,2)) AS MONEY FROM EMPLOYEE;



-- 5. Department-wise salary sum for each job
SELECT
JOB,
SUM(CASE WHEN DEPTNO = 10 THEN SAL ELSE 0 END) AS DEPT_10,
SUM(CASE WHEN DEPTNO = 20 THEN SAL ELSE 0 END) AS DEPT_20,
SUM(CASE WHEN DEPTNO = 30 THEN SAL ELSE 0 END) AS DEPT_30,
SUM(CASE WHEN DEPTNO = 40 THEN SAL ELSE 0 END) AS DEPT_40,
SUM(SAL) AS TOTAL_PAY
FROM EMPLOYEE 
GROUP BY JOB;



-- 6. Count employees and year-wise joining report
SELECT
COUNT(*) AS TOTAL_EMPLOYEE,
SUM(CASE WHEN YEAR(HIREDATE) = 1980 THEN 1 ELSE 0 END) AS Y_1980,
SUM(CASE WHEN YEAR(HIREDATE) = 1981 THEN 1 ELSE 0 END) AS Y_1981,
SUM(CASE WHEN YEAR(HIREDATE) = 1982 THEN 1 ELSE 0 END) AS Y_1982,
SUM(CASE WHEN YEAR(HIREDATE) = 1983 THEN 1 ELSE 0 END) AS Y_1983
FROM EMPLOYEE;



-- 7. Find the last Sunday of a given date (2026-05-28)
SELECT 
  DATE_SUB(
    LAST_DAY('2026-05-28'),
    INTERVAL (DAYOFWEEK(LAST_DAY('2026-05-28')) - 1) DAY
  ) AS LAST_SUNDAY;


-- 8. Count employees department-wise
SELECT DEPTNO, COUNT(*) AS TOTAL_EMPLOYEE 
FROM EMPLOYEE 
GROUP BY DEPTNO;


-- 9. Count employees job-wise

SELECT
JOB,
COUNT(*) AS TOTAL_EMPLOYEE 
FROM EMPLOYEE GROUP BY JOB;


-- 10. Department-wise total salary
SELECT
DEPTNO,
SUM(SAL) AS TOTAL_SAL
FROM EMPLOYEE GROUP BY DEPTNO;






