USE EMPLOYEE;

-- 1. DISPLAY ALL EMPLOYEES WITH THEIR DEPARTMENT NAME
SELECT 
    E.*,
    D.DNAME AS DEPARTMENT_NAME
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
USING (DEPTNO);



-- 2. DISPLAY EMPLOYEES WHOSE MANAGER NAME IS JONES
SELECT
    E.ENAME AS EMPLOYEE_NAME,
    M.ENAME AS MANAGER_NAME
FROM EMPLOYEE E
JOIN EMPLOYEE M
ON E.MGR = M.EMPNO
WHERE M.ENAME = 'JONES';



-- 3. DISPLAY EMPLOYEE NAME, JOB, MANAGER NAME, DEPARTMENT NAME AND GRADE
SELECT
    E.ENAME AS EMPLOYEE_NAME,
    E.JOB AS JOB,
    M.ENAME AS MANAGER_NAME,
    D.DNAME AS DEPARTMENT_NAME,
    S.GRADE AS PAY_LEVEL_GRADE
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
USING (DEPTNO)
JOIN EMPLOYEE M
ON E.MGR = M.EMPNO
JOIN SALGRADE S
ON E.SAL BETWEEN S.MINPAY AND S.MAXPAY
ORDER BY DNAME;



-- 4. DISPLAY EMPLOYEES EXCEPT CLERK
SELECT 
    E.ENAME,
    E.JOB,
    D.DNAME,
    E.SAL
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO
WHERE E.JOB <> 'CLERK'
ORDER BY E.SAL DESC;



-- 5. DISPLAY EMPLOYEE NAME, JOB AND MANAGER NAME INCLUDING NO MANAGER
SELECT 
    E.ENAME,
    E.JOB,
    IFNULL(M.ENAME, 'NO MANAGER') AS MANAGER_NAME
FROM EMPLOYEE E
LEFT JOIN EMPLOYEE M
ON E.MGR = M.EMPNO;



-- 6. DISPLAY EMPLOYEES WHOSE ANNUAL SALARY IS GREATER THAN 36000
SELECT 
    E.ENAME AS EMPLOYEE_NAME,
    E.JOB AS JOB,
    E.SAL * 12 AS ANNUAL_SALARY,
    D.DEPTNO AS DEPARTMENT_NO,
    D.DNAME AS DEPARTMENT_NAME,
    S.GRADE AS GRADE_PAY
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
USING (DEPTNO)
JOIN SALGRADE S
ON E.SAL BETWEEN S.MINPAY AND S.MAXPAY
WHERE E.SAL * 12 >= 36000
AND E.JOB <> 'CLERK';



-- 7. DISPLAY EMPLOYEES WHOSE ANNUAL SALARY IS GREATER THAN 30000
SELECT 
    E.ENAME AS EMPLOYEE_NAME,
    E.JOB AS JOB,
    E.SAL * 12 AS ANNUAL_SALARY,
    D.DEPTNO AS DEPARTMENT_NO,
    D.DNAME AS DEPARTMENT_NAME,
    S.GRADE AS GRADE_PAY
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
USING (DEPTNO)
JOIN SALGRADE S
ON E.SAL BETWEEN S.MINPAY AND S.MAXPAY
WHERE E.SAL * 12 >= 30000
AND E.JOB <> 'CLERK';



-- 8. DISPLAY EMPLOYEE AND MANAGER DETAILS
SELECT 
    E.EMPNO,
    E.ENAME,
    IFNULL(M.EMPNO, 'NO MANAGER') AS MANAGER_NO,
    IFNULL(M.ENAME, 'NO MANAGER') AS MANAGER_NAME
FROM EMPLOYEE E
LEFT JOIN EMPLOYEE M
ON E.MGR = M.EMPNO;



-- 9. DISPLAY DEPARTMENT NAME, DEPARTMENT NUMBER AND TOTAL SALARY
SELECT 
    D.DNAME,
    D.DEPTNO,
    SUM(E.SAL) AS TOTAL_SALARY
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO, D.DNAME;



-- 10. DISPLAY EMPLOYEE NUMBER, NAME AND DEPARTMENT LOCATION
SELECT 
    E.EMPNO,
    E.ENAME,
    D.LOC
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;



-- 11. DISPLAY EMPLOYEE NAME AND DEPARTMENT NAME
SELECT 
    E.ENAME,
    D.DNAME
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;


