USE EMPLOYEE;

SELECT DISTINCT JOB
            FROM EMPLOYEE;
            


SELECT * FROM EMPLOYEE WHERE DEPTNO = 30;


SELECT * FROM DEPARTMENT WHERE DEPTNO > 20;


SELECT * FROM EMPLOYEE WHERE JOB IN ('MANAGER','CLERK') AND DEPTNO = 30;

SELECT EMPNO, ENAME, DEPTNO FROM EMPLOYEE WHERE JOB = 'CLERK';

SELECT * FROM EMPLOYEE WHERE JOB = 'MANAGER' AND DEPTNO <> 30;


SELECT * FROM EMPLOYEE  WHERE JOB NOT IN ('MANAGER','CLERK') AND DEPTNO = 10;


SELECT EMPNO, ENAME, JOB FROM EMPLOYEE WHERE SAL BETWEEN 1200 AND 1400;


SELECT ENAME, DEPTNO FROM EMPLOYEE WHERE JOB IN ('CLERK', 'ANALYST', 'SALESMAN');



SELECT * FROM EMPLOYEE WHERE ENAME LIKE 'M%';




